
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class attributeConfig_AttributeRes : Luban.BeanBase
{
    public attributeConfig_AttributeRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["genusId"].IsNumber) { throw new SerializationException(); }  GenusId = _buf["genusId"]; }
        { if(!_buf["genusValue"].IsNumber) { throw new SerializationException(); }  GenusValue = _buf["genusValue"]; }
        { if(!_buf["genusScale"].IsNumber) { throw new SerializationException(); }  GenusScale = _buf["genusScale"]; }
        { if(!_buf["genusLabelDesc"].IsString) { throw new SerializationException(); }  GenusLabelDesc = _buf["genusLabelDesc"]; }
        { if(!_buf["genusLabelValue"].IsString) { throw new SerializationException(); }  GenusLabelValue = _buf["genusLabelValue"]; }
    }

    public static attributeConfig_AttributeRes DeserializeattributeConfig_AttributeRes(JSONNode _buf)
    {
        return new attributeConfig_AttributeRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 属性功能id
    /// </summary>
    public readonly int GenusId;
    /// <summary>
    /// 加减数值
    /// </summary>
    public readonly float GenusValue;
    /// <summary>
    /// 倍率数值
    /// </summary>
    public readonly float GenusScale;
    /// <summary>
    /// 属性名
    /// </summary>
    public readonly string GenusLabelDesc;
    /// <summary>
    /// 属性值
    /// </summary>
    public readonly string GenusLabelValue;
   
    public const int __ID__ = -439036379;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "genusId:" + GenusId + ","
        + "genusValue:" + GenusValue + ","
        + "genusScale:" + GenusScale + ","
        + "genusLabelDesc:" + GenusLabelDesc + ","
        + "genusLabelValue:" + GenusLabelValue + ","
        + "}";
    }
}

}

