
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BoxRes_Boxgenerate : Luban.BeanBase
{
    public BoxRes_Boxgenerate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["Boxhp"].IsNumber) { throw new SerializationException(); }  Boxhp = _buf["Boxhp"]; }
        { if(!_buf["delay"].IsNumber) { throw new SerializationException(); }  Delay = _buf["delay"]; }
        { if(!_buf["interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["interval"]; }
        { if(!_buf["weight_prop"].IsNumber) { throw new SerializationException(); }  WeightProp = _buf["weight_prop"]; }
        { if(!_buf["schedule"].IsNumber) { throw new SerializationException(); }  Schedule = _buf["schedule"]; }
    }

    public static BoxRes_Boxgenerate DeserializeBoxRes_Boxgenerate(JSONNode _buf)
    {
        return new BoxRes_Boxgenerate(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 宝箱血量
    /// </summary>
    public readonly int Boxhp;
    /// <summary>
    /// 出生延迟（ms）
    /// </summary>
    public readonly int Delay;
    /// <summary>
    /// 生成间隔(ms)
    /// </summary>
    public readonly float Interval;
    /// <summary>
    /// 额外获得道具概率(%)
    /// </summary>
    public readonly float WeightProp;
    /// <summary>
    /// 常规增加技能进度（%）
    /// </summary>
    public readonly int Schedule;
   
    public const int __ID__ = -2097238570;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "Boxhp:" + Boxhp + ","
        + "delay:" + Delay + ","
        + "interval:" + Interval + ","
        + "weightProp:" + WeightProp + ","
        + "schedule:" + Schedule + ","
        + "}";
    }
}

}

