
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BoxRes_boxcontent : Luban.BeanBase
{
    public BoxRes_boxcontent(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["resource"].IsString) { throw new SerializationException(); }  Resource = _buf["resource"]; }
        { if(!_buf["sound"].IsString) { throw new SerializationException(); }  Sound = _buf["sound"]; }
        { var __json0 = _buf["fires"]; if(!__json0.IsArray) { throw new SerializationException(); } Fires = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Fires.Add(__v0); }   }
        { if(!_buf["livesTimes"].IsNumber) { throw new SerializationException(); }  LivesTimes = _buf["livesTimes"]; }
        { if(!_buf["mergeTimes"].IsNumber) { throw new SerializationException(); }  MergeTimes = _buf["mergeTimes"]; }
        { if(!_buf["mergeType"].IsNumber) { throw new SerializationException(); }  MergeType = _buf["mergeType"]; }
        { if(!_buf["rewardres"].IsNumber) { throw new SerializationException(); }  Rewardres = _buf["rewardres"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { if(!_buf["note"].IsString) { throw new SerializationException(); }  Note = _buf["note"]; }
    }

    public static BoxRes_boxcontent DeserializeBoxRes_boxcontent(JSONNode _buf)
    {
        return new BoxRes_boxcontent(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 龙骨资源
    /// </summary>
    public readonly string Resource;
    /// <summary>
    /// 释放音效
    /// </summary>
    public readonly string Sound;
    /// <summary>
    /// 发射数组
    /// </summary>
    public readonly System.Collections.Generic.List<int> Fires;
    /// <summary>
    /// 生效次数
    /// </summary>
    public readonly int LivesTimes;
    /// <summary>
    /// 最多叠加次数（相同id）
    /// </summary>
    public readonly int MergeTimes;
    /// <summary>
    /// 叠加方式（相同id）
    /// </summary>
    public readonly int MergeType;
    /// <summary>
    /// 金币奖励倍数
    /// </summary>
    public readonly int Rewardres;
    /// <summary>
    /// 获得权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 宝箱金币平均产出倍数
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = -1722175528;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "des:" + Des + ","
        + "icon:" + Icon + ","
        + "resource:" + Resource + ","
        + "sound:" + Sound + ","
        + "fires:" + Luban.StringUtil.CollectionToString(Fires) + ","
        + "livesTimes:" + LivesTimes + ","
        + "mergeTimes:" + MergeTimes + ","
        + "mergeType:" + MergeType + ","
        + "rewardres:" + Rewardres + ","
        + "weight:" + Weight + ","
        + "note:" + Note + ","
        + "}";
    }
}

}

