
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BoxRes_Boxgenerate : Luban.BeanBase
{
    public BoxRes_Boxgenerate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["Boxhp"].IsNumber) { throw new SerializationException(); }  Boxhp = _buf["Boxhp"]; }
        { if(!_buf["delay"].IsNumber) { throw new SerializationException(); }  Delay = _buf["delay"]; }
        { if(!_buf["interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["interval"]; }
        { var __json0 = _buf["appearance"]; if(!__json0.IsArray) { throw new SerializationException(); } Appearance = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Appearance.Add(__v0); }   }
    }

    public static BoxRes_Boxgenerate DeserializeBoxRes_Boxgenerate(JSONNode _buf)
    {
        return new BoxRes_Boxgenerate(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 宝箱血量
    /// </summary>
    public readonly int Boxhp;
    /// <summary>
    /// 出生延迟（ms）
    /// </summary>
    public readonly int Delay;
    /// <summary>
    /// 生成间隔(ms)
    /// </summary>
    public readonly float Interval;
    /// <summary>
    /// 宝箱外观随机
    /// </summary>
    public readonly System.Collections.Generic.List<int> Appearance;
   
    public const int __ID__ = -2097238570;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "Boxhp:" + Boxhp + ","
        + "delay:" + Delay + ","
        + "interval:" + Interval + ","
        + "appearance:" + Luban.StringUtil.CollectionToString(Appearance) + ","
        + "}";
    }
}

}

