
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class competenceConfig_AbilityRes : Luban.BeanBase
{
    public competenceConfig_AbilityRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["skill"].IsNumber) { throw new SerializationException(); }  Skill = _buf["skill"]; }
        { if(!_buf["buff"].IsNumber) { throw new SerializationException(); }  Buff = _buf["buff"]; }
        { if(!_buf["gold"].IsNumber) { throw new SerializationException(); }  Gold = _buf["gold"]; }
        { if(!_buf["replace"].IsNumber) { throw new SerializationException(); }  Replace = _buf["replace"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { if(!_buf["note"].IsString) { throw new SerializationException(); }  Note = _buf["note"]; }
    }

    public static competenceConfig_AbilityRes DeserializecompetenceConfig_AbilityRes(JSONNode _buf)
    {
        return new competenceConfig_AbilityRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 获得Skill
    /// </summary>
    public readonly int Skill;
    /// <summary>
    /// 获得Buff
    /// </summary>
    public readonly int Buff;
    /// <summary>
    /// 获得金币
    /// </summary>
    public readonly int Gold;
    /// <summary>
    /// 是否替换当前武器
    /// </summary>
    public readonly int Replace;
    /// <summary>
    /// 能力品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = 1927219082;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skill:" + Skill + ","
        + "buff:" + Buff + ","
        + "gold:" + Gold + ","
        + "replace:" + Replace + ","
        + "quality:" + Quality + ","
        + "note:" + Note + ","
        + "}";
    }
}

}

