
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DoorRes_Doorgenerate : Luban.BeanBase
{
    public DoorRes_Doorgenerate(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["delay"].IsNumber) { throw new SerializationException(); }  Delay = _buf["delay"]; }
        { if(!_buf["interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["interval"]; }
        { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }
    }

    public static DoorRes_Doorgenerate DeserializeDoorRes_Doorgenerate(JSONNode _buf)
    {
        return new DoorRes_Doorgenerate(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 出生延迟（ms）
    /// </summary>
    public readonly int Delay;
    /// <summary>
    /// 生成间隔(ms)
    /// </summary>
    public readonly int Interval;
    /// <summary>
    /// 生成个数
    /// </summary>
    public readonly int Number;
   
    public const int __ID__ = -2132724624;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "delay:" + Delay + ","
        + "interval:" + Interval + ","
        + "number:" + Number + ","
        + "}";
    }
}

}

