
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DoorRes_Doorcontent : Luban.BeanBase
{
    public DoorRes_Doorcontent(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["definition"].IsNumber) { throw new SerializationException(); }  Definition = _buf["definition"]; }
        { if(!_buf["attributes"].IsNumber) { throw new SerializationException(); }  Attributes = _buf["attributes"]; }
        { if(!_buf["genusValue"].IsNumber) { throw new SerializationException(); }  GenusValue = _buf["genusValue"]; }
        { if(!_buf["genusScale"].IsNumber) { throw new SerializationException(); }  GenusScale = _buf["genusScale"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
    }

    public static DoorRes_Doorcontent DeserializeDoorRes_Doorcontent(JSONNode _buf)
    {
        return new DoorRes_Doorcontent(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 1为BUFF，2为DEBUFF
    /// </summary>
    public readonly int Definition;
    /// <summary>
    /// 属性定义
    /// </summary>
    public readonly int Attributes;
    /// <summary>
    /// 加减数值
    /// </summary>
    public readonly float GenusValue;
    /// <summary>
    /// 倍率数值
    /// </summary>
    public readonly double GenusScale;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = 1794165278;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "definition:" + Definition + ","
        + "attributes:" + Attributes + ","
        + "genusValue:" + GenusValue + ","
        + "genusScale:" + GenusScale + ","
        + "weight:" + Weight + ","
        + "}";
    }
}

}

