
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class equipmentConfig_LevelRes : Luban.BeanBase
{
    public equipmentConfig_LevelRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["starrating"].IsNumber) { throw new SerializationException(); }  Starrating = _buf["starrating"]; }
        { var __json0 = _buf["attr"]; if(!__json0.IsArray) { throw new SerializationException(); } Attr = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Attr.Add(__v0); }   }
        { var __json0 = _buf["skills"]; if(!__json0.IsArray) { throw new SerializationException(); } Skills = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills.Add(__v0); }   }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { var __json0 = _buf["attributes"]; if(!__json0.IsArray) { throw new SerializationException(); } Attributes = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Attributes.Add(__v0); }   }
    }

    public static equipmentConfig_LevelRes DeserializeequipmentConfig_LevelRes(JSONNode _buf)
    {
        return new equipmentConfig_LevelRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 物品id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 装备星级
    /// </summary>
    public readonly int Starrating;
    /// <summary>
    /// 装备属性
    /// </summary>
    public readonly System.Collections.Generic.List<int> Attr;
    /// <summary>
    /// 拥有SKILL
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 拥有BUFF
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    /// <summary>
    /// 拥有ATTRIBUTE
    /// </summary>
    public readonly System.Collections.Generic.List<int> Attributes;
   
    public const int __ID__ = 227649419;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemId:" + ItemId + ","
        + "icon:" + Icon + ","
        + "starrating:" + Starrating + ","
        + "attr:" + Luban.StringUtil.CollectionToString(Attr) + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "attributes:" + Luban.StringUtil.CollectionToString(Attributes) + ","
        + "}";
    }
}

}

