
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class equipmentConfig_EquipRes : Luban.BeanBase
{
    public equipmentConfig_EquipRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["skeleton"].IsString) { throw new SerializationException(); }  Skeleton = _buf["skeleton"]; }
        { if(!_buf["note"].IsString) { throw new SerializationException(); }  Note = _buf["note"]; }
    }

    public static equipmentConfig_EquipRes DeserializeequipmentConfig_EquipRes(JSONNode _buf)
    {
        return new equipmentConfig_EquipRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 龙骨资源
    /// </summary>
    public readonly string Skeleton;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = -1346794657;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skeleton:" + Skeleton + ","
        + "note:" + Note + ","
        + "}";
    }
}

}

