
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GlobalResnew_Global : Luban.BeanBase
{
    public GlobalResnew_Global(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["intValue"].IsNumber) { throw new SerializationException(); }  IntValue = _buf["intValue"]; }
        { if(!_buf["floatValue"].IsNumber) { throw new SerializationException(); }  FloatValue = _buf["floatValue"]; }
        { if(!_buf["stringValue"].IsString) { throw new SerializationException(); }  StringValue = _buf["stringValue"]; }
        { if(!_buf["note"].IsString) { throw new SerializationException(); }  Note = _buf["note"]; }
    }

    public static GlobalResnew_Global DeserializeGlobalResnew_Global(JSONNode _buf)
    {
        return new GlobalResnew_Global(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数值变量值
    /// </summary>
    public readonly long IntValue;
    /// <summary>
    /// 浮点变量值
    /// </summary>
    public readonly float FloatValue;
    /// <summary>
    /// 字符串变量值
    /// </summary>
    public readonly string StringValue;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = -742271777;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "intValue:" + IntValue + ","
        + "floatValue:" + FloatValue + ","
        + "stringValue:" + StringValue + ","
        + "note:" + Note + ","
        + "}";
    }
}

}

