
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class heroConfig_HeroLevelRes : Luban.BeanBase
{
    public heroConfig_HeroLevelRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["heroId"].IsNumber) { throw new SerializationException(); }  HeroId = _buf["heroId"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["atk"].IsNumber) { throw new SerializationException(); }  Atk = _buf["atk"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
    }

    public static heroConfig_HeroLevelRes DeserializeheroConfig_HeroLevelRes(JSONNode _buf)
    {
        return new heroConfig_HeroLevelRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 英雄id
    /// </summary>
    public readonly int HeroId;
    /// <summary>
    /// 英雄等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Atk;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly float Hp;
   
    public const int __ID__ = -1755420615;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "heroId:" + HeroId + ","
        + "level:" + Level + ","
        + "atk:" + Atk + ","
        + "hp:" + Hp + ","
        + "}";
    }
}

}

