
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class itemConfig_ItemRes : Luban.BeanBase
{
    public itemConfig_ItemRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["subtype"].IsNumber) { throw new SerializationException(); }  Subtype = _buf["subtype"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
    }

    public static itemConfig_ItemRes DeserializeitemConfig_ItemRes(JSONNode _buf)
    {
        return new itemConfig_ItemRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 物品名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 子类型
    /// </summary>
    public readonly int Subtype;
    /// <summary>
    /// 物品描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 物品图标
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -559295901;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "name:" + Name + ","
        + "subtype:" + Subtype + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}

