
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class JumpConfig : Luban.BeanBase
{
    public JumpConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsBoolean) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["URL"].IsString) { throw new SerializationException(); }  URL = _buf["URL"]; }
    }

    public static JumpConfig DeserializeJumpConfig(JSONNode _buf)
    {
        return new JumpConfig(_buf);
    }

    /// <summary>
    /// 是否开启
    /// </summary>
    public readonly bool ID;
    /// <summary>
    /// 网址
    /// </summary>
    public readonly string URL;
   
    public const int __ID__ = 952100144;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "URL:" + URL + ","
        + "}";
    }
}

}

