
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class languageConfig_Language : Luban.BeanBase
{
    public languageConfig_Language(JSONNode _buf) 
    {
        { if(!_buf["keyname"].IsString) { throw new SerializationException(); }  Keyname = _buf["keyname"]; }
        { if(!_buf["module"].IsString) { throw new SerializationException(); }  Module = _buf["module"]; }
        { if(!_buf["zhongwen"].IsString) { throw new SerializationException(); }  Zhongwen = _buf["zhongwen"]; }
        { if(!_buf["yingwen"].IsString) { throw new SerializationException(); }  Yingwen = _buf["yingwen"]; }
        { if(!_buf["putaoya"].IsString) { throw new SerializationException(); }  Putaoya = _buf["putaoya"]; }
        { if(!_buf["eluosi"].IsString) { throw new SerializationException(); }  Eluosi = _buf["eluosi"]; }
        { if(!_buf["español"].IsString) { throw new SerializationException(); }  Español = _buf["español"]; }
        { if(!_buf["taiyu"].IsString) { throw new SerializationException(); }  Taiyu = _buf["taiyu"]; }
        { if(!_buf["日本語"].IsString) { throw new SerializationException(); }  日本語 = _buf["日本語"]; }
        { if(!_buf["hanyu"].IsString) { throw new SerializationException(); }  Hanyu = _buf["hanyu"]; }
        { if(!_buf["yinniyu"].IsString) { throw new SerializationException(); }  Yinniyu = _buf["yinniyu"]; }
        { if(!_buf["malaiyu"].IsString) { throw new SerializationException(); }  Malaiyu = _buf["malaiyu"]; }
        { if(!_buf["fuwenben"].IsBoolean) { throw new SerializationException(); }  Fuwenben = _buf["fuwenben"]; }
    }

    public static languageConfig_Language DeserializelanguageConfig_Language(JSONNode _buf)
    {
        return new languageConfig_Language(_buf);
    }

    /// <summary>
    /// 钥匙名
    /// </summary>
    public readonly string Keyname;
    /// <summary>
    /// 模块
    /// </summary>
    public readonly string Module;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Zhongwen;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string Yingwen;
    /// <summary>
    /// 葡萄牙语
    /// </summary>
    public readonly string Putaoya;
    /// <summary>
    /// 俄罗斯语
    /// </summary>
    public readonly string Eluosi;
    /// <summary>
    /// 西班牙语
    /// </summary>
    public readonly string Español;
    /// <summary>
    /// 泰语
    /// </summary>
    public readonly string Taiyu;
    /// <summary>
    /// 日语
    /// </summary>
    public readonly string 日本語;
    /// <summary>
    /// 韩语
    /// </summary>
    public readonly string Hanyu;
    /// <summary>
    /// 印尼语
    /// </summary>
    public readonly string Yinniyu;
    /// <summary>
    /// 马来语
    /// </summary>
    public readonly string Malaiyu;
    /// <summary>
    /// isRichText
    /// </summary>
    public readonly bool Fuwenben;
   
    public const int __ID__ = -745457315;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "keyname:" + Keyname + ","
        + "module:" + Module + ","
        + "zhongwen:" + Zhongwen + ","
        + "yingwen:" + Yingwen + ","
        + "putaoya:" + Putaoya + ","
        + "eluosi:" + Eluosi + ","
        + "español:" + Español + ","
        + "taiyu:" + Taiyu + ","
        + "日本語:" + 日本語 + ","
        + "hanyu:" + Hanyu + ","
        + "yinniyu:" + Yinniyu + ","
        + "malaiyu:" + Malaiyu + ","
        + "fuwenben:" + Fuwenben + ","
        + "}";
    }
}

}

