
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfignew_danConfig : Luban.BeanBase
{
    public levelConfignew_danConfig(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["dan"].IsString) { throw new SerializationException(); }  Dan = _buf["dan"]; }
        { if(!_buf["Star_rating"].IsNumber) { throw new SerializationException(); }  StarRating = _buf["Star_rating"]; }
        { if(!_buf["promotion_reward"].IsNumber) { throw new SerializationException(); }  PromotionReward = _buf["promotion_reward"]; }
    }

    public static levelConfignew_danConfig DeserializelevelConfignew_danConfig(JSONNode _buf)
    {
        return new levelConfignew_danConfig(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly string Dan;
    /// <summary>
    /// 星级
    /// </summary>
    public readonly int StarRating;
    /// <summary>
    /// 升段金币奖励奖励
    /// </summary>
    public readonly int PromotionReward;
   
    public const int __ID__ = 2034142254;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "dan:" + Dan + ","
        + "StarRating:" + StarRating + ","
        + "promotionReward:" + PromotionReward + ","
        + "}";
    }
}

}

