
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_PhysiqueRes : Luban.BeanBase
{
    public levelConfig_PhysiqueRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["lv"].IsNumber) { throw new SerializationException(); }  Lv = _buf["lv"]; }
        { if(!_buf["cuipi_atk"].IsNumber) { throw new SerializationException(); }  CuipiAtk = _buf["cuipi_atk"]; }
        { if(!_buf["jin_atk"].IsNumber) { throw new SerializationException(); }  JinAtk = _buf["jin_atk"]; }
        { if(!_buf["yuan_atk"].IsNumber) { throw new SerializationException(); }  YuanAtk = _buf["yuan_atk"]; }
        { if(!_buf["jing_atk"].IsNumber) { throw new SerializationException(); }  JingAtk = _buf["jing_atk"]; }
        { if(!_buf["boss_atk"].IsNumber) { throw new SerializationException(); }  BossAtk = _buf["boss_atk"]; }
        { if(!_buf["cuipi_hp"].IsNumber) { throw new SerializationException(); }  CuipiHp = _buf["cuipi_hp"]; }
        { if(!_buf["jin_hp"].IsNumber) { throw new SerializationException(); }  JinHp = _buf["jin_hp"]; }
        { if(!_buf["yuan_hp"].IsNumber) { throw new SerializationException(); }  YuanHp = _buf["yuan_hp"]; }
        { if(!_buf["jing_hp"].IsNumber) { throw new SerializationException(); }  JingHp = _buf["jing_hp"]; }
        { if(!_buf["boss_hp"].IsNumber) { throw new SerializationException(); }  BossHp = _buf["boss_hp"]; }
        { if(!_buf["cuipi_spd"].IsNumber) { throw new SerializationException(); }  CuipiSpd = _buf["cuipi_spd"]; }
        { if(!_buf["jin_spd"].IsNumber) { throw new SerializationException(); }  JinSpd = _buf["jin_spd"]; }
        { if(!_buf["yuan_spd"].IsNumber) { throw new SerializationException(); }  YuanSpd = _buf["yuan_spd"]; }
        { if(!_buf["jing_spd"].IsNumber) { throw new SerializationException(); }  JingSpd = _buf["jing_spd"]; }
        { if(!_buf["boss_spd"].IsNumber) { throw new SerializationException(); }  BossSpd = _buf["boss_spd"]; }
        { var __json0 = _buf["cuipi_money"]; if(!__json0.IsArray) { throw new SerializationException(); } CuipiMoney = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CuipiMoney.Add(__v0); }   }
        { var __json0 = _buf["jin_money"]; if(!__json0.IsArray) { throw new SerializationException(); } JinMoney = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  JinMoney.Add(__v0); }   }
        { var __json0 = _buf["yuan_money"]; if(!__json0.IsArray) { throw new SerializationException(); } YuanMoney = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  YuanMoney.Add(__v0); }   }
        { var __json0 = _buf["jing_money"]; if(!__json0.IsArray) { throw new SerializationException(); } JingMoney = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  JingMoney.Add(__v0); }   }
        { var __json0 = _buf["boss_money"]; if(!__json0.IsArray) { throw new SerializationException(); } BossMoney = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BossMoney.Add(__v0); }   }
        { if(!_buf["box_min"].IsNumber) { throw new SerializationException(); }  BoxMin = _buf["box_min"]; }
        { if(!_buf["box_max"].IsNumber) { throw new SerializationException(); }  BoxMax = _buf["box_max"]; }
    }

    public static levelConfig_PhysiqueRes DeserializelevelConfig_PhysiqueRes(JSONNode _buf)
    {
        return new levelConfig_PhysiqueRes(_buf);
    }

    public readonly int Id;
    public readonly int Lv;
    /// <summary>
    /// Atk 攻击
    /// </summary>
    public readonly float CuipiAtk;
    public readonly float JinAtk;
    public readonly float YuanAtk;
    public readonly float JingAtk;
    public readonly float BossAtk;
    /// <summary>
    /// Hp 血量
    /// </summary>
    public readonly float CuipiHp;
    public readonly float JinHp;
    public readonly float YuanHp;
    public readonly float JingHp;
    public readonly float BossHp;
    /// <summary>
    /// Spd 移速
    /// </summary>
    public readonly float CuipiSpd;
    public readonly float JinSpd;
    public readonly float YuanSpd;
    public readonly float JingSpd;
    public readonly float BossSpd;
    /// <summary>
    /// $掉落的钱
    /// </summary>
    public readonly System.Collections.Generic.List<int> CuipiMoney;
    public readonly System.Collections.Generic.List<int> JinMoney;
    public readonly System.Collections.Generic.List<int> YuanMoney;
    public readonly System.Collections.Generic.List<int> JingMoney;
    public readonly System.Collections.Generic.List<int> BossMoney;
    /// <summary>
    /// 宝箱血量范围
    /// </summary>
    public readonly int BoxMin;
    public readonly int BoxMax;
   
    public const int __ID__ = -299544195;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "lv:" + Lv + ","
        + "cuipiAtk:" + CuipiAtk + ","
        + "jinAtk:" + JinAtk + ","
        + "yuanAtk:" + YuanAtk + ","
        + "jingAtk:" + JingAtk + ","
        + "bossAtk:" + BossAtk + ","
        + "cuipiHp:" + CuipiHp + ","
        + "jinHp:" + JinHp + ","
        + "yuanHp:" + YuanHp + ","
        + "jingHp:" + JingHp + ","
        + "bossHp:" + BossHp + ","
        + "cuipiSpd:" + CuipiSpd + ","
        + "jinSpd:" + JinSpd + ","
        + "yuanSpd:" + YuanSpd + ","
        + "jingSpd:" + JingSpd + ","
        + "bossSpd:" + BossSpd + ","
        + "cuipiMoney:" + Luban.StringUtil.CollectionToString(CuipiMoney) + ","
        + "jinMoney:" + Luban.StringUtil.CollectionToString(JinMoney) + ","
        + "yuanMoney:" + Luban.StringUtil.CollectionToString(YuanMoney) + ","
        + "jingMoney:" + Luban.StringUtil.CollectionToString(JingMoney) + ","
        + "bossMoney:" + Luban.StringUtil.CollectionToString(BossMoney) + ","
        + "boxMin:" + BoxMin + ","
        + "boxMax:" + BoxMax + ","
        + "}";
    }
}

}

