
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_waveRes : Luban.BeanBase
{
    public levelConfig_waveRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["tiledMapId"]; if(!__json0.IsArray) { throw new SerializationException(); } TiledMapId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  TiledMapId.Add(__v0); }   }
    }

    public static levelConfig_waveRes DeserializelevelConfig_waveRes(JSONNode _buf)
    {
        return new levelConfig_waveRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 波数随机刷怪标识范围
    /// </summary>
    public readonly System.Collections.Generic.List<int> TiledMapId;
   
    public const int __ID__ = 966416270;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "tiledMapId:" + Luban.StringUtil.CollectionToString(TiledMapId) + ","
        + "}";
    }
}

}

