
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfignew_settlementConfig : Luban.BeanBase
{
    public levelConfignew_settlementConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Awards"].IsString) { throw new SerializationException(); }  Awards = _buf["Awards"]; }
        { var __json0 = _buf["multiplier"]; if(!__json0.IsArray) { throw new SerializationException(); } Multiplier = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Multiplier.Add(__v0); }   }
        { var __json0 = _buf["probability"]; if(!__json0.IsArray) { throw new SerializationException(); } Probability = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Probability.Add(__v0); }   }
    }

    public static levelConfignew_settlementConfig DeserializelevelConfignew_settlementConfig(JSONNode _buf)
    {
        return new levelConfignew_settlementConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 奖项
    /// </summary>
    public readonly string Awards;
    /// <summary>
    /// 关卡结算奖励倍数
    /// </summary>
    public readonly System.Collections.Generic.List<float> Multiplier;
    /// <summary>
    /// 概率(%)
    /// </summary>
    public readonly System.Collections.Generic.List<int> Probability;
   
    public const int __ID__ = -147633296;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Awards:" + Awards + ","
        + "multiplier:" + Luban.StringUtil.CollectionToString(Multiplier) + ","
        + "probability:" + Luban.StringUtil.CollectionToString(Probability) + ","
        + "}";
    }
}

}

