
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_EnemyRes : Luban.BeanBase
{
    public levelConfig_EnemyRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["monsterId"]; if(!__json0.IsArray) { throw new SerializationException(); } MonsterId = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MonsterId.Add(__v0); }   }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["delay"].IsNumber) { throw new SerializationException(); }  Delay = _buf["delay"]; }
        { if(!_buf["interval"].IsNumber) { throw new SerializationException(); }  Interval = _buf["interval"]; }
        { if(!_buf["note1"].IsNumber) { throw new SerializationException(); }  Note1 = _buf["note1"]; }
        { if(!_buf["note2"].IsString) { throw new SerializationException(); }  Note2 = _buf["note2"]; }
    }

    public static levelConfig_EnemyRes DeserializelevelConfig_EnemyRes(JSONNode _buf)
    {
        return new levelConfig_EnemyRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 怪物id
    /// </summary>
    public readonly System.Collections.Generic.List<int> MonsterId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 出生延迟（ms）
    /// </summary>
    public readonly int Delay;
    /// <summary>
    /// 出生间隔（ms）
    /// </summary>
    public readonly int Interval;
    /// <summary>
    /// 持续时间(s)
    /// </summary>
    public readonly float Note1;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly string Note2;
   
    public const int __ID__ = 1122411601;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterId:" + Luban.StringUtil.CollectionToString(MonsterId) + ","
        + "count:" + Count + ","
        + "delay:" + Delay + ","
        + "interval:" + Interval + ","
        + "note1:" + Note1 + ","
        + "note2:" + Note2 + ","
        + "}";
    }
}

}

