
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfignew_danConfig : Luban.BeanBase
{
    public levelConfignew_danConfig(JSONNode _buf) 
    {
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["dan"].IsString) { throw new SerializationException(); }  Dan = _buf["dan"]; }
        { if(!_buf["Star_rating"].IsNumber) { throw new SerializationException(); }  StarRating = _buf["Star_rating"]; }
        { if(!_buf["promotion_reward"].IsNumber) { throw new SerializationException(); }  PromotionReward = _buf["promotion_reward"]; }
        { if(!_buf["Blood_coefficient"].IsNumber) { throw new SerializationException(); }  BloodCoefficient = _buf["Blood_coefficient"]; }
        { if(!_buf["Number_coefficient"].IsNumber) { throw new SerializationException(); }  NumberCoefficient = _buf["Number_coefficient"]; }
        { if(!_buf["note1"].IsNumber) { throw new SerializationException(); }  Note1 = _buf["note1"]; }
        { if(!_buf["note2"].IsNumber) { throw new SerializationException(); }  Note2 = _buf["note2"]; }
        { if(!_buf["note3"].IsNumber) { throw new SerializationException(); }  Note3 = _buf["note3"]; }
    }

    public static levelConfignew_danConfig DeserializelevelConfignew_danConfig(JSONNode _buf)
    {
        return new levelConfignew_danConfig(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 段位
    /// </summary>
    public readonly string Dan;
    /// <summary>
    /// 星级
    /// </summary>
    public readonly int StarRating;
    /// <summary>
    /// 升段金币奖励奖励
    /// </summary>
    public readonly int PromotionReward;
    /// <summary>
    /// 怪物血量系数与金币掉落系数
    /// </summary>
    public readonly float BloodCoefficient;
    /// <summary>
    /// 怪物数量系数
    /// </summary>
    public readonly float NumberCoefficient;
    public readonly float Note1;
    public readonly float Note2;
    /// <summary>
    /// 血量系数备份
    /// </summary>
    public readonly float Note3;
   
    public const int __ID__ = 2034142254;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "dan:" + Dan + ","
        + "StarRating:" + StarRating + ","
        + "promotionReward:" + PromotionReward + ","
        + "BloodCoefficient:" + BloodCoefficient + ","
        + "NumberCoefficient:" + NumberCoefficient + ","
        + "note1:" + Note1 + ","
        + "note2:" + Note2 + ","
        + "note3:" + Note3 + ","
        + "}";
    }
}

}

