
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_TopicRes : Luban.BeanBase
{
    public levelConfig_TopicRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["topic"]; if(!__json0.IsArray) { throw new SerializationException(); } Topic = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Topic.Add(__v0); }   }
    }

    public static levelConfig_TopicRes DeserializelevelConfig_TopicRes(JSONNode _buf)
    {
        return new levelConfig_TopicRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly System.Collections.Generic.List<int> Topic;
   
    public const int __ID__ = -1602129590;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "topic:" + Luban.StringUtil.CollectionToString(Topic) + ","
        + "}";
    }
}

}

