
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_DoorRes : Luban.BeanBase
{
    public levelConfig_DoorRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["brushout1"]; if(!__json0.IsArray) { throw new SerializationException(); } Brushout1 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Brushout1.Add(__v0); }   }
        { var __json0 = _buf["brushout2"]; if(!__json0.IsArray) { throw new SerializationException(); } Brushout2 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Brushout2.Add(__v0); }   }
        { var __json0 = _buf["brushout3"]; if(!__json0.IsArray) { throw new SerializationException(); } Brushout3 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Brushout3.Add(__v0); }   }
        { var __json0 = _buf["brushout4"]; if(!__json0.IsArray) { throw new SerializationException(); } Brushout4 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Brushout4.Add(__v0); }   }
        { if(!_buf["note1"].IsString) { throw new SerializationException(); }  Note1 = _buf["note1"]; }
        { if(!_buf["note2"].IsString) { throw new SerializationException(); }  Note2 = _buf["note2"]; }
    }

    public static levelConfig_DoorRes DeserializelevelConfig_DoorRes(JSONNode _buf)
    {
        return new levelConfig_DoorRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 增益随机刷出标识范围1
    /// </summary>
    public readonly System.Collections.Generic.List<int> Brushout1;
    /// <summary>
    /// 增益随机刷出标识范围2
    /// </summary>
    public readonly System.Collections.Generic.List<int> Brushout2;
    /// <summary>
    /// 增益随机刷出标识范围3
    /// </summary>
    public readonly System.Collections.Generic.List<int> Brushout3;
    /// <summary>
    /// 增益随机刷出标识范围4
    /// </summary>
    public readonly System.Collections.Generic.List<int> Brushout4;
    /// <summary>
    /// 备注1
    /// </summary>
    public readonly string Note1;
    /// <summary>
    /// 备注2
    /// </summary>
    public readonly string Note2;
   
    public const int __ID__ = -951867751;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "brushout1:" + Luban.StringUtil.CollectionToString(Brushout1) + ","
        + "brushout2:" + Luban.StringUtil.CollectionToString(Brushout2) + ","
        + "brushout3:" + Luban.StringUtil.CollectionToString(Brushout3) + ","
        + "brushout4:" + Luban.StringUtil.CollectionToString(Brushout4) + ","
        + "note1:" + Note1 + ","
        + "note2:" + Note2 + ","
        + "}";
    }
}

}

