
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_NestRes : Luban.BeanBase
{
    public levelConfig_NestRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { var __json0 = _buf["monster1"]; if(!__json0.IsArray) { throw new SerializationException(); } Monster1 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Monster1.Add(__v0); }   }
        { var __json0 = _buf["monster2"]; if(!__json0.IsArray) { throw new SerializationException(); } Monster2 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Monster2.Add(__v0); }   }
        { var __json0 = _buf["monster3"]; if(!__json0.IsArray) { throw new SerializationException(); } Monster3 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Monster3.Add(__v0); }   }
        { var __json0 = _buf["monster4"]; if(!__json0.IsArray) { throw new SerializationException(); } Monster4 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Monster4.Add(__v0); }   }
        { var __json0 = _buf["brushout5"]; if(!__json0.IsArray) { throw new SerializationException(); } Brushout5 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Brushout5.Add(__v0); }   }
        { var __json0 = _buf["box1"]; if(!__json0.IsArray) { throw new SerializationException(); } Box1 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Box1.Add(__v0); }   }
        { var __json0 = _buf["door1"]; if(!__json0.IsArray) { throw new SerializationException(); } Door1 = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Door1.Add(__v0); }   }
    }

    public static levelConfig_NestRes DeserializelevelConfig_NestRes(JSONNode _buf)
    {
        return new levelConfig_NestRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 怪物组(脆皮）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Monster1;
    /// <summary>
    /// 怪物组（近战）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Monster2;
    /// <summary>
    /// 怪物组（远程）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Monster3;
    /// <summary>
    /// 怪物组（精英）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Monster4;
    /// <summary>
    /// 怪物组（BOSS）
    /// </summary>
    public readonly System.Collections.Generic.List<int> Brushout5;
    /// <summary>
    /// 宝箱组
    /// </summary>
    public readonly System.Collections.Generic.List<int> Box1;
    /// <summary>
    /// 门组
    /// </summary>
    public readonly System.Collections.Generic.List<int> Door1;
   
    public const int __ID__ = -949303377;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "monster1:" + Luban.StringUtil.CollectionToString(Monster1) + ","
        + "monster2:" + Luban.StringUtil.CollectionToString(Monster2) + ","
        + "monster3:" + Luban.StringUtil.CollectionToString(Monster3) + ","
        + "monster4:" + Luban.StringUtil.CollectionToString(Monster4) + ","
        + "brushout5:" + Luban.StringUtil.CollectionToString(Brushout5) + ","
        + "box1:" + Luban.StringUtil.CollectionToString(Box1) + ","
        + "door1:" + Luban.StringUtil.CollectionToString(Door1) + ","
        + "}";
    }
}

}

