
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class levelConfig_DialogueRes : Luban.BeanBase
{
    public levelConfig_DialogueRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["speaker"].IsNumber) { throw new SerializationException(); }  Speaker = _buf["speaker"]; }
        { if(!_buf["dialogue"].IsString) { throw new SerializationException(); }  Dialogue = _buf["dialogue"]; }
    }

    public static levelConfig_DialogueRes DeserializelevelConfig_DialogueRes(JSONNode _buf)
    {
        return new levelConfig_DialogueRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型(1为英雄2为怪兽)
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// ID
    /// </summary>
    public readonly int Speaker;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly string Dialogue;
   
    public const int __ID__ = 1450749103;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "speaker:" + Speaker + ","
        + "dialogue:" + Dialogue + ","
        + "}";
    }
}

}

