
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class monsterConfig_MonsterRes : Luban.BeanBase
{
    public monsterConfig_MonsterRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { var __json0 = _buf["btree"]; if(!__json0.IsArray) { throw new SerializationException(); } Btree = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Btree.Add(__v0); }   }
        { var __json0 = _buf["physique"]; if(!__json0.IsArray) { throw new SerializationException(); } Physique = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Physique.Add(__v0); }   }
        { var __json0 = _buf["skills"]; if(!__json0.IsArray) { throw new SerializationException(); } Skills = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills.Add(__v0); }   }
        { var __json0 = _buf["buffs"]; if(!__json0.IsArray) { throw new SerializationException(); } Buffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Buffs.Add(__v0); }   }
        { if(!_buf["skeleton"].IsString) { throw new SerializationException(); }  Skeleton = _buf["skeleton"]; }
        { if(!_buf["Scale"].IsNumber) { throw new SerializationException(); }  Scale = _buf["Scale"]; }
        { if(!_buf["weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["weight"]; }
        { if(!_buf["isBoss"].IsNumber) { throw new SerializationException(); }  IsBoss = _buf["isBoss"]; }
    }

    public static monsterConfig_MonsterRes DeserializemonsterConfig_MonsterRes(JSONNode _buf)
    {
        return new monsterConfig_MonsterRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 远程攻击间隔
    /// </summary>
    public readonly System.Collections.Generic.List<int> Btree;
    /// <summary>
    /// 体质属性（关卡表PhysiqueRes）
    /// </summary>
    public readonly System.Collections.Generic.List<string> Physique;
    /// <summary>
    /// Skill
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// Buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> Buffs;
    /// <summary>
    /// 龙骨资源
    /// </summary>
    public readonly string Skeleton;
    /// <summary>
    /// 缩放比例
    /// </summary>
    public readonly int Scale;
    /// <summary>
    /// 重量
    /// </summary>
    public readonly float Weight;
    /// <summary>
    /// 是否boss
    /// </summary>
    public readonly int IsBoss;
   
    public const int __ID__ = 955484905;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "btree:" + Luban.StringUtil.CollectionToString(Btree) + ","
        + "physique:" + Luban.StringUtil.CollectionToString(Physique) + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "buffs:" + Luban.StringUtil.CollectionToString(Buffs) + ","
        + "skeleton:" + Skeleton + ","
        + "Scale:" + Scale + ","
        + "weight:" + Weight + ","
        + "isBoss:" + IsBoss + ","
        + "}";
    }
}

}

