
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class playerConfig_PlayerLevelRes : Luban.BeanBase
{
    public playerConfig_PlayerLevelRes(JSONNode _buf) 
    {
        { if(!_buf["lv"].IsNumber) { throw new SerializationException(); }  Lv = _buf["lv"]; }
        { if(!_buf["exp"].IsString) { throw new SerializationException(); }  Exp = _buf["exp"]; }
        { if(!_buf["total"].IsNumber) { throw new SerializationException(); }  Total = _buf["total"]; }
        { var __json0 = _buf["skills"]; if(!__json0.IsArray) { throw new SerializationException(); } Skills = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills.Add(__v0); }   }
        { if(!_buf["Blood"].IsNumber) { throw new SerializationException(); }  Blood = _buf["Blood"]; }
        { if(!_buf["note"].IsNumber) { throw new SerializationException(); }  Note = _buf["note"]; }
    }

    public static playerConfig_PlayerLevelRes DeserializeplayerConfig_PlayerLevelRes(JSONNode _buf)
    {
        return new playerConfig_PlayerLevelRes(_buf);
    }

    /// <summary>
    /// 玩家等级
    /// </summary>
    public readonly int Lv;
    /// <summary>
    /// 升级所需经验
    /// </summary>
    public readonly string Exp;
    /// <summary>
    /// 当前等级最高子弹价格
    /// </summary>
    public readonly long Total;
    /// <summary>
    /// 当前等级最强武器
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 当前等级玩家血量
    /// </summary>
    public readonly long Blood;
    /// <summary>
    /// 备注
    /// </summary>
    public readonly int Note;
   
    public const int __ID__ = 1121901273;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "lv:" + Lv + ","
        + "exp:" + Exp + ","
        + "total:" + Total + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "Blood:" + Blood + ","
        + "note:" + Note + ","
        + "}";
    }
}

}

