
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class skillConfig_StrategyEnum : Luban.BeanBase
{
    public skillConfig_StrategyEnum(JSONNode _buf) 
    {
        { if(!_buf["enumId"].IsString) { throw new SerializationException(); }  EnumId = _buf["enumId"]; }
        { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }
        { if(!_buf["note1"].IsString) { throw new SerializationException(); }  Note1 = _buf["note1"]; }
        { if(!_buf["note2"].IsString) { throw new SerializationException(); }  Note2 = _buf["note2"]; }
        { if(!_buf["note3"].IsString) { throw new SerializationException(); }  Note3 = _buf["note3"]; }
    }

    public static skillConfig_StrategyEnum DeserializeskillConfig_StrategyEnum(JSONNode _buf)
    {
        return new skillConfig_StrategyEnum(_buf);
    }

    /// <summary>
    /// 发射行径枚举
    /// </summary>
    public readonly string EnumId;
    /// <summary>
    /// 枚举值
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 名称说明
    /// </summary>
    public readonly string Note1;
    /// <summary>
    /// strategy参数说明
    /// </summary>
    public readonly string Note2;
    /// <summary>
    /// 参数解释(圆周半径：默认为100，即屏幕左侧到右侧的距离)
    /// </summary>
    public readonly string Note3;
   
    public const int __ID__ = -685022464;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enumId:" + EnumId + ","
        + "number:" + Number + ","
        + "note1:" + Note1 + ","
        + "note2:" + Note2 + ","
        + "note3:" + Note3 + ","
        + "}";
    }
}

}

