
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class skillConfig_SkillRes : Luban.BeanBase
{
    public skillConfig_SkillRes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["resource"].IsString) { throw new SerializationException(); }  Resource = _buf["resource"]; }
        { if(!_buf["sound"].IsString) { throw new SerializationException(); }  Sound = _buf["sound"]; }
        { if(!_buf["cd"].IsNumber) { throw new SerializationException(); }  Cd = _buf["cd"]; }
        { var __json0 = _buf["fires"]; if(!__json0.IsArray) { throw new SerializationException(); } Fires = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Fires.Add(__v0); }   }
        { var __json0 = _buf["ownBuffs"]; if(!__json0.IsArray) { throw new SerializationException(); } OwnBuffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  OwnBuffs.Add(__v0); }   }
        { var __json0 = _buf["enemyBuffs"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyBuffs = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EnemyBuffs.Add(__v0); }   }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["afterms"].IsNumber) { throw new SerializationException(); }  Afterms = _buf["afterms"]; }
        { if(!_buf["isForWeapon"].IsNumber) { throw new SerializationException(); }  IsForWeapon = _buf["isForWeapon"]; }
        { if(!_buf["isAnyTime"].IsNumber) { throw new SerializationException(); }  IsAnyTime = _buf["isAnyTime"]; }
        { if(!_buf["isCross"].IsNumber) { throw new SerializationException(); }  IsCross = _buf["isCross"]; }
        { if(!_buf["isForever"].IsNumber) { throw new SerializationException(); }  IsForever = _buf["isForever"]; }
        { if(!_buf["livesTimes"].IsNumber) { throw new SerializationException(); }  LivesTimes = _buf["livesTimes"]; }
        { if(!_buf["mergeTimes"].IsNumber) { throw new SerializationException(); }  MergeTimes = _buf["mergeTimes"]; }
        { if(!_buf["mergeType"].IsNumber) { throw new SerializationException(); }  MergeType = _buf["mergeType"]; }
    }

    public static skillConfig_SkillRes DeserializeskillConfig_SkillRes(JSONNode _buf)
    {
        return new skillConfig_SkillRes(_buf);
    }

    /// <summary>
    /// 配置id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 龙骨资源
    /// </summary>
    public readonly string Resource;
    /// <summary>
    /// 释放音效
    /// </summary>
    public readonly string Sound;
    /// <summary>
    /// 冷却时间（ms）
    /// </summary>
    public readonly int Cd;
    /// <summary>
    /// 发射数组
    /// </summary>
    public readonly System.Collections.Generic.List<int> Fires;
    /// <summary>
    /// 激活时给自己加BUFF
    /// </summary>
    public readonly System.Collections.Generic.List<int> OwnBuffs;
    /// <summary>
    /// 攻击给敌人加BUFF
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnemyBuffs;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 后摇耗时（ms）
    /// </summary>
    public readonly int Afterms;
    /// <summary>
    /// 是否武器技能（与冷却属性有关联）
    /// </summary>
    public readonly int IsForWeapon;
    /// <summary>
    /// 是否随时能释放
    /// </summary>
    public readonly int IsAnyTime;
    /// <summary>
    /// 是否穿墙瞄准
    /// </summary>
    public readonly int IsCross;
    /// <summary>
    /// 是否永久
    /// </summary>
    public readonly int IsForever;
    /// <summary>
    /// 生效次数
    /// </summary>
    public readonly int LivesTimes;
    /// <summary>
    /// 最多叠加次数（相同id）
    /// </summary>
    public readonly int MergeTimes;
    /// <summary>
    /// 叠加方式（相同id）
    /// </summary>
    public readonly int MergeType;
   
    public const int __ID__ = -1175746949;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "des:" + Des + ","
        + "icon:" + Icon + ","
        + "resource:" + Resource + ","
        + "sound:" + Sound + ","
        + "cd:" + Cd + ","
        + "fires:" + Luban.StringUtil.CollectionToString(Fires) + ","
        + "ownBuffs:" + Luban.StringUtil.CollectionToString(OwnBuffs) + ","
        + "enemyBuffs:" + Luban.StringUtil.CollectionToString(EnemyBuffs) + ","
        + "priority:" + Priority + ","
        + "afterms:" + Afterms + ","
        + "isForWeapon:" + IsForWeapon + ","
        + "isAnyTime:" + IsAnyTime + ","
        + "isCross:" + IsCross + ","
        + "isForever:" + IsForever + ","
        + "livesTimes:" + LivesTimes + ","
        + "mergeTimes:" + MergeTimes + ","
        + "mergeType:" + MergeType + ","
        + "}";
    }
}

}

