
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class soundConfignew_soundConfig : Luban.BeanBase
{
    public soundConfignew_soundConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["beijingMP3"].IsString) { throw new SerializationException(); }  BeijingMP3 = _buf["beijingMP3"]; }
        { if(!_buf["zhandouMP3"].IsString) { throw new SerializationException(); }  ZhandouMP3 = _buf["zhandouMP3"]; }
        { if(!_buf["CoinMp3"].IsString) { throw new SerializationException(); }  CoinMp3 = _buf["CoinMp3"]; }
    }

    public static soundConfignew_soundConfig DeserializesoundConfignew_soundConfig(JSONNode _buf)
    {
        return new soundConfignew_soundConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 主界面背景音乐
    /// </summary>
    public readonly string BeijingMP3;
    /// <summary>
    /// 战斗界面背景音乐
    /// </summary>
    public readonly string ZhandouMP3;
    /// <summary>
    /// 金币掉落音效
    /// </summary>
    public readonly string CoinMp3;
   
    public const int __ID__ = -846729279;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "beijingMP3:" + BeijingMP3 + ","
        + "zhandouMP3:" + ZhandouMP3 + ","
        + "CoinMp3:" + CoinMp3 + ","
        + "}";
    }
}

}

