
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_AttributeResattributeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, attributeConfig_AttributeRes> _dataMap;
    private readonly System.Collections.Generic.List<attributeConfig_AttributeRes> _dataList;
    
    public Table_AttributeResattributeConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, attributeConfig_AttributeRes>();
        _dataList = new System.Collections.Generic.List<attributeConfig_AttributeRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            attributeConfig_AttributeRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = attributeConfig_AttributeRes.DeserializeattributeConfig_AttributeRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, attributeConfig_AttributeRes> DataMap => _dataMap;
    public System.Collections.Generic.List<attributeConfig_AttributeRes> DataList => _dataList;

    public attributeConfig_AttributeRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public attributeConfig_AttributeRes Get(int key) => _dataMap[key];
    public attributeConfig_AttributeRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

