
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_transmitConfig
{
    private readonly System.Collections.Generic.Dictionary<int, transmitConfig_transmitConfig> _dataMap;
    private readonly System.Collections.Generic.List<transmitConfig_transmitConfig> _dataList;
    
    public Table_transmitConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, transmitConfig_transmitConfig>();
        _dataList = new System.Collections.Generic.List<transmitConfig_transmitConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            transmitConfig_transmitConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = transmitConfig_transmitConfig.DeserializetransmitConfig_transmitConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, transmitConfig_transmitConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<transmitConfig_transmitConfig> DataList => _dataList;

    public transmitConfig_transmitConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public transmitConfig_transmitConfig Get(int key) => _dataMap[key];
    public transmitConfig_transmitConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

