
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_monster
{
    private readonly System.Collections.Generic.Dictionary<int, monsterConfignew_monster> _dataMap;
    private readonly System.Collections.Generic.List<monsterConfignew_monster> _dataList;
    
    public Table_monster(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, monsterConfignew_monster>();
        _dataList = new System.Collections.Generic.List<monsterConfignew_monster>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            monsterConfignew_monster _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = monsterConfignew_monster.DeserializemonsterConfignew_monster(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, monsterConfignew_monster> DataMap => _dataMap;
    public System.Collections.Generic.List<monsterConfignew_monster> DataList => _dataList;

    public monsterConfignew_monster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public monsterConfignew_monster Get(int key) => _dataMap[key];
    public monsterConfignew_monster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

