
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_PlayerLevelRes
{
    private readonly System.Collections.Generic.Dictionary<int, playerConfig_PlayerLevelRes> _dataMap;
    private readonly System.Collections.Generic.List<playerConfig_PlayerLevelRes> _dataList;
    
    public Table_PlayerLevelRes(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, playerConfig_PlayerLevelRes>();
        _dataList = new System.Collections.Generic.List<playerConfig_PlayerLevelRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            playerConfig_PlayerLevelRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = playerConfig_PlayerLevelRes.DeserializeplayerConfig_PlayerLevelRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Lv, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, playerConfig_PlayerLevelRes> DataMap => _dataMap;
    public System.Collections.Generic.List<playerConfig_PlayerLevelRes> DataList => _dataList;

    public playerConfig_PlayerLevelRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public playerConfig_PlayerLevelRes Get(int key) => _dataMap[key];
    public playerConfig_PlayerLevelRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

