
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_MonsterResmonsterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, monsterConfig_MonsterRes> _dataMap;
    private readonly System.Collections.Generic.List<monsterConfig_MonsterRes> _dataList;
    
    public Table_MonsterResmonsterConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, monsterConfig_MonsterRes>();
        _dataList = new System.Collections.Generic.List<monsterConfig_MonsterRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            monsterConfig_MonsterRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = monsterConfig_MonsterRes.DeserializemonsterConfig_MonsterRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, monsterConfig_MonsterRes> DataMap => _dataMap;
    public System.Collections.Generic.List<monsterConfig_MonsterRes> DataList => _dataList;

    public monsterConfig_MonsterRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public monsterConfig_MonsterRes Get(int key) => _dataMap[key];
    public monsterConfig_MonsterRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

