
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_FireResskillConfig
{
    private readonly System.Collections.Generic.Dictionary<int, skillConfig_FireRes> _dataMap;
    private readonly System.Collections.Generic.List<skillConfig_FireRes> _dataList;
    
    public Table_FireResskillConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, skillConfig_FireRes>();
        _dataList = new System.Collections.Generic.List<skillConfig_FireRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            skillConfig_FireRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = skillConfig_FireRes.DeserializeskillConfig_FireRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, skillConfig_FireRes> DataMap => _dataMap;
    public System.Collections.Generic.List<skillConfig_FireRes> DataList => _dataList;

    public skillConfig_FireRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public skillConfig_FireRes Get(int key) => _dataMap[key];
    public skillConfig_FireRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

