
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_Doorcontent
{
    private readonly System.Collections.Generic.Dictionary<int, DoorRes_Doorcontent> _dataMap;
    private readonly System.Collections.Generic.List<DoorRes_Doorcontent> _dataList;
    
    public Table_Doorcontent(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DoorRes_Doorcontent>();
        _dataList = new System.Collections.Generic.List<DoorRes_Doorcontent>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DoorRes_Doorcontent _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DoorRes_Doorcontent.DeserializeDoorRes_Doorcontent(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DoorRes_Doorcontent> DataMap => _dataMap;
    public System.Collections.Generic.List<DoorRes_Doorcontent> DataList => _dataList;

    public DoorRes_Doorcontent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DoorRes_Doorcontent Get(int key) => _dataMap[key];
    public DoorRes_Doorcontent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

