
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_danConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfignew_danConfig> _dataMap;
    private readonly System.Collections.Generic.List<levelConfignew_danConfig> _dataList;
    
    public Table_danConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfignew_danConfig>();
        _dataList = new System.Collections.Generic.List<levelConfignew_danConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfignew_danConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfignew_danConfig.DeserializelevelConfignew_danConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfignew_danConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfignew_danConfig> DataList => _dataList;

    public levelConfignew_danConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfignew_danConfig Get(int key) => _dataMap[key];
    public levelConfignew_danConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

