
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_soundConfig
{
    private readonly System.Collections.Generic.Dictionary<int, soundConfignew_soundConfig> _dataMap;
    private readonly System.Collections.Generic.List<soundConfignew_soundConfig> _dataList;
    
    public Table_soundConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, soundConfignew_soundConfig>();
        _dataList = new System.Collections.Generic.List<soundConfignew_soundConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            soundConfignew_soundConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = soundConfignew_soundConfig.DeserializesoundConfignew_soundConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, soundConfignew_soundConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<soundConfignew_soundConfig> DataList => _dataList;

    public soundConfignew_soundConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public soundConfignew_soundConfig Get(int key) => _dataMap[key];
    public soundConfignew_soundConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

