
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_boxcontent
{
    private readonly System.Collections.Generic.Dictionary<int, BoxRes_boxcontent> _dataMap;
    private readonly System.Collections.Generic.List<BoxRes_boxcontent> _dataList;
    
    public Table_boxcontent(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BoxRes_boxcontent>();
        _dataList = new System.Collections.Generic.List<BoxRes_boxcontent>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BoxRes_boxcontent _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BoxRes_boxcontent.DeserializeBoxRes_boxcontent(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BoxRes_boxcontent> DataMap => _dataMap;
    public System.Collections.Generic.List<BoxRes_boxcontent> DataList => _dataList;

    public BoxRes_boxcontent GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BoxRes_boxcontent Get(int key) => _dataMap[key];
    public BoxRes_boxcontent this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

