
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_EnemyReslevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfig_EnemyRes> _dataMap;
    private readonly System.Collections.Generic.List<levelConfig_EnemyRes> _dataList;
    
    public Table_EnemyReslevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfig_EnemyRes>();
        _dataList = new System.Collections.Generic.List<levelConfig_EnemyRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfig_EnemyRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfig_EnemyRes.DeserializelevelConfig_EnemyRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfig_EnemyRes> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfig_EnemyRes> DataList => _dataList;

    public levelConfig_EnemyRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfig_EnemyRes Get(int key) => _dataMap[key];
    public levelConfig_EnemyRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

