
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_DialogueReslevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfig_DialogueRes> _dataMap;
    private readonly System.Collections.Generic.List<levelConfig_DialogueRes> _dataList;
    
    public Table_DialogueReslevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfig_DialogueRes>();
        _dataList = new System.Collections.Generic.List<levelConfig_DialogueRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfig_DialogueRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfig_DialogueRes.DeserializelevelConfig_DialogueRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfig_DialogueRes> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfig_DialogueRes> DataList => _dataList;

    public levelConfig_DialogueRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfig_DialogueRes Get(int key) => _dataMap[key];
    public levelConfig_DialogueRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

