
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_DailyConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DailyConfig> _dataMap;
    private readonly System.Collections.Generic.List<DailyConfig> _dataList;
    
    public Table_DailyConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DailyConfig>();
        _dataList = new System.Collections.Generic.List<DailyConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DailyConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DailyConfig.DeserializeDailyConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DailyConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DailyConfig> DataList => _dataList;

    public DailyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DailyConfig Get(int key) => _dataMap[key];
    public DailyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

