
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_Global
{
    private readonly System.Collections.Generic.Dictionary<int, GlobalResnew_Global> _dataMap;
    private readonly System.Collections.Generic.List<GlobalResnew_Global> _dataList;
    
    public Table_Global(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GlobalResnew_Global>();
        _dataList = new System.Collections.Generic.List<GlobalResnew_Global>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GlobalResnew_Global _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GlobalResnew_Global.DeserializeGlobalResnew_Global(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GlobalResnew_Global> DataMap => _dataMap;
    public System.Collections.Generic.List<GlobalResnew_Global> DataList => _dataList;

    public GlobalResnew_Global GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GlobalResnew_Global Get(int key) => _dataMap[key];
    public GlobalResnew_Global this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

