
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_turntableConfig
{
    private readonly System.Collections.Generic.Dictionary<int, turntableConfig> _dataMap;
    private readonly System.Collections.Generic.List<turntableConfig> _dataList;
    
    public Table_turntableConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, turntableConfig>();
        _dataList = new System.Collections.Generic.List<turntableConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            turntableConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = turntableConfig.DeserializeturntableConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, turntableConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<turntableConfig> DataList => _dataList;

    public turntableConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public turntableConfig Get(int key) => _dataMap[key];
    public turntableConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

