
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_LevelResequipmentConfi
{
    private readonly System.Collections.Generic.Dictionary<int, equipmentConfig_LevelRes> _dataMap;
    private readonly System.Collections.Generic.List<equipmentConfig_LevelRes> _dataList;
    
    public Table_LevelResequipmentConfi(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, equipmentConfig_LevelRes>();
        _dataList = new System.Collections.Generic.List<equipmentConfig_LevelRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            equipmentConfig_LevelRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = equipmentConfig_LevelRes.DeserializeequipmentConfig_LevelRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, equipmentConfig_LevelRes> DataMap => _dataMap;
    public System.Collections.Generic.List<equipmentConfig_LevelRes> DataList => _dataList;

    public equipmentConfig_LevelRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public equipmentConfig_LevelRes Get(int key) => _dataMap[key];
    public equipmentConfig_LevelRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

