
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_EquipResequipmentConfi
{
    private readonly System.Collections.Generic.Dictionary<int, equipmentConfig_EquipRes> _dataMap;
    private readonly System.Collections.Generic.List<equipmentConfig_EquipRes> _dataList;
    
    public Table_EquipResequipmentConfi(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, equipmentConfig_EquipRes>();
        _dataList = new System.Collections.Generic.List<equipmentConfig_EquipRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            equipmentConfig_EquipRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = equipmentConfig_EquipRes.DeserializeequipmentConfig_EquipRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, equipmentConfig_EquipRes> DataMap => _dataMap;
    public System.Collections.Generic.List<equipmentConfig_EquipRes> DataList => _dataList;

    public equipmentConfig_EquipRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public equipmentConfig_EquipRes Get(int key) => _dataMap[key];
    public equipmentConfig_EquipRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

