
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_settlementConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfignew_settlementConfig> _dataMap;
    private readonly System.Collections.Generic.List<levelConfignew_settlementConfig> _dataList;
    
    public Table_settlementConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfignew_settlementConfig>();
        _dataList = new System.Collections.Generic.List<levelConfignew_settlementConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfignew_settlementConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfignew_settlementConfig.DeserializelevelConfignew_settlementConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfignew_settlementConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfignew_settlementConfig> DataList => _dataList;

    public levelConfignew_settlementConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfignew_settlementConfig Get(int key) => _dataMap[key];
    public levelConfignew_settlementConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

