
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_BuffResskillConfig
{
    private readonly System.Collections.Generic.Dictionary<int, skillConfig_BuffRes> _dataMap;
    private readonly System.Collections.Generic.List<skillConfig_BuffRes> _dataList;
    
    public Table_BuffResskillConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, skillConfig_BuffRes>();
        _dataList = new System.Collections.Generic.List<skillConfig_BuffRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            skillConfig_BuffRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = skillConfig_BuffRes.DeserializeskillConfig_BuffRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, skillConfig_BuffRes> DataMap => _dataMap;
    public System.Collections.Generic.List<skillConfig_BuffRes> DataList => _dataList;

    public skillConfig_BuffRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public skillConfig_BuffRes Get(int key) => _dataMap[key];
    public skillConfig_BuffRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

