
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_DoorTypeReslevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfig_DoorTypeRes> _dataMap;
    private readonly System.Collections.Generic.List<levelConfig_DoorTypeRes> _dataList;
    
    public Table_DoorTypeReslevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfig_DoorTypeRes>();
        _dataList = new System.Collections.Generic.List<levelConfig_DoorTypeRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfig_DoorTypeRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfig_DoorTypeRes.DeserializelevelConfig_DoorTypeRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfig_DoorTypeRes> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfig_DoorTypeRes> DataList => _dataList;

    public levelConfig_DoorTypeRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfig_DoorTypeRes Get(int key) => _dataMap[key];
    public levelConfig_DoorTypeRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

