
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_illustrate
{
    private readonly System.Collections.Generic.Dictionary<string, transmitConfig_illustrate> _dataMap;
    private readonly System.Collections.Generic.List<transmitConfig_illustrate> _dataList;
    
    public Table_illustrate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, transmitConfig_illustrate>();
        _dataList = new System.Collections.Generic.List<transmitConfig_illustrate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            transmitConfig_illustrate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = transmitConfig_illustrate.DeserializetransmitConfig_illustrate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EnumId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, transmitConfig_illustrate> DataMap => _dataMap;
    public System.Collections.Generic.List<transmitConfig_illustrate> DataList => _dataList;

    public transmitConfig_illustrate GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public transmitConfig_illustrate Get(string key) => _dataMap[key];
    public transmitConfig_illustrate this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

