
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_BulletResskillConfig
{
    private readonly System.Collections.Generic.Dictionary<int, skillConfig_BulletRes> _dataMap;
    private readonly System.Collections.Generic.List<skillConfig_BulletRes> _dataList;
    
    public Table_BulletResskillConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, skillConfig_BulletRes>();
        _dataList = new System.Collections.Generic.List<skillConfig_BulletRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            skillConfig_BulletRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = skillConfig_BulletRes.DeserializeskillConfig_BulletRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, skillConfig_BulletRes> DataMap => _dataMap;
    public System.Collections.Generic.List<skillConfig_BulletRes> DataList => _dataList;

    public skillConfig_BulletRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public skillConfig_BulletRes Get(int key) => _dataMap[key];
    public skillConfig_BulletRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

