
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_GlobalResConfig
{
    private readonly System.Collections.Generic.Dictionary<int, GlobalResConfig_GlobalRes> _dataMap;
    private readonly System.Collections.Generic.List<GlobalResConfig_GlobalRes> _dataList;
    
    public Table_GlobalResConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GlobalResConfig_GlobalRes>();
        _dataList = new System.Collections.Generic.List<GlobalResConfig_GlobalRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GlobalResConfig_GlobalRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GlobalResConfig_GlobalRes.DeserializeGlobalResConfig_GlobalRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GlobalResConfig_GlobalRes> DataMap => _dataMap;
    public System.Collections.Generic.List<GlobalResConfig_GlobalRes> DataList => _dataList;

    public GlobalResConfig_GlobalRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GlobalResConfig_GlobalRes Get(int key) => _dataMap[key];
    public GlobalResConfig_GlobalRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

