
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_HeroReshero
{
    private readonly System.Collections.Generic.Dictionary<int, playerConfig_HeroRes> _dataMap;
    private readonly System.Collections.Generic.List<playerConfig_HeroRes> _dataList;
    
    public Table_HeroReshero(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, playerConfig_HeroRes>();
        _dataList = new System.Collections.Generic.List<playerConfig_HeroRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            playerConfig_HeroRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = playerConfig_HeroRes.DeserializeplayerConfig_HeroRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, playerConfig_HeroRes> DataMap => _dataMap;
    public System.Collections.Generic.List<playerConfig_HeroRes> DataList => _dataList;

    public playerConfig_HeroRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public playerConfig_HeroRes Get(int key) => _dataMap[key];
    public playerConfig_HeroRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

