
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_HeroLevelResheroConfig
{
    private readonly System.Collections.Generic.Dictionary<int, heroConfig_HeroLevelRes> _dataMap;
    private readonly System.Collections.Generic.List<heroConfig_HeroLevelRes> _dataList;
    
    public Table_HeroLevelResheroConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, heroConfig_HeroLevelRes>();
        _dataList = new System.Collections.Generic.List<heroConfig_HeroLevelRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            heroConfig_HeroLevelRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = heroConfig_HeroLevelRes.DeserializeheroConfig_HeroLevelRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, heroConfig_HeroLevelRes> DataMap => _dataMap;
    public System.Collections.Generic.List<heroConfig_HeroLevelRes> DataList => _dataList;

    public heroConfig_HeroLevelRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public heroConfig_HeroLevelRes Get(int key) => _dataMap[key];
    public heroConfig_HeroLevelRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

