
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_ItemResitemConfig
{
    private readonly System.Collections.Generic.Dictionary<int, itemConfig_ItemRes> _dataMap;
    private readonly System.Collections.Generic.List<itemConfig_ItemRes> _dataList;
    
    public Table_ItemResitemConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, itemConfig_ItemRes>();
        _dataList = new System.Collections.Generic.List<itemConfig_ItemRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            itemConfig_ItemRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = itemConfig_ItemRes.DeserializeitemConfig_ItemRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, itemConfig_ItemRes> DataMap => _dataMap;
    public System.Collections.Generic.List<itemConfig_ItemRes> DataList => _dataList;

    public itemConfig_ItemRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public itemConfig_ItemRes Get(int key) => _dataMap[key];
    public itemConfig_ItemRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

