
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_SkillResskillConfig
{
    private readonly System.Collections.Generic.Dictionary<int, skillConfig_SkillRes> _dataMap;
    private readonly System.Collections.Generic.List<skillConfig_SkillRes> _dataList;
    
    public Table_SkillResskillConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, skillConfig_SkillRes>();
        _dataList = new System.Collections.Generic.List<skillConfig_SkillRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            skillConfig_SkillRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = skillConfig_SkillRes.DeserializeskillConfig_SkillRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, skillConfig_SkillRes> DataMap => _dataMap;
    public System.Collections.Generic.List<skillConfig_SkillRes> DataList => _dataList;

    public skillConfig_SkillRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public skillConfig_SkillRes Get(int key) => _dataMap[key];
    public skillConfig_SkillRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

