
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_DoorReslevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfig_DoorRes> _dataMap;
    private readonly System.Collections.Generic.List<levelConfig_DoorRes> _dataList;
    
    public Table_DoorReslevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfig_DoorRes>();
        _dataList = new System.Collections.Generic.List<levelConfig_DoorRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfig_DoorRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfig_DoorRes.DeserializelevelConfig_DoorRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfig_DoorRes> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfig_DoorRes> DataList => _dataList;

    public levelConfig_DoorRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfig_DoorRes Get(int key) => _dataMap[key];
    public levelConfig_DoorRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

