
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_levelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfignew_levelConfig> _dataMap;
    private readonly System.Collections.Generic.List<levelConfignew_levelConfig> _dataList;
    
    public Table_levelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfignew_levelConfig>();
        _dataList = new System.Collections.Generic.List<levelConfignew_levelConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfignew_levelConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfignew_levelConfig.DeserializelevelConfignew_levelConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfignew_levelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfignew_levelConfig> DataList => _dataList;

    public levelConfignew_levelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfignew_levelConfig Get(int key) => _dataMap[key];
    public levelConfignew_levelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

