
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_BoxRewardReslevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfig_BoxRewardRes> _dataMap;
    private readonly System.Collections.Generic.List<levelConfig_BoxRewardRes> _dataList;
    
    public Table_BoxRewardReslevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfig_BoxRewardRes>();
        _dataList = new System.Collections.Generic.List<levelConfig_BoxRewardRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfig_BoxRewardRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfig_BoxRewardRes.DeserializelevelConfig_BoxRewardRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfig_BoxRewardRes> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfig_BoxRewardRes> DataList => _dataList;

    public levelConfig_BoxRewardRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfig_BoxRewardRes Get(int key) => _dataMap[key];
    public levelConfig_BoxRewardRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

