
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_ItemEnumitemConfig
{
    private readonly System.Collections.Generic.Dictionary<string, itemConfig_ItemEnum> _dataMap;
    private readonly System.Collections.Generic.List<itemConfig_ItemEnum> _dataList;
    
    public Table_ItemEnumitemConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, itemConfig_ItemEnum>();
        _dataList = new System.Collections.Generic.List<itemConfig_ItemEnum>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            itemConfig_ItemEnum _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = itemConfig_ItemEnum.DeserializeitemConfig_ItemEnum(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EnumId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, itemConfig_ItemEnum> DataMap => _dataMap;
    public System.Collections.Generic.List<itemConfig_ItemEnum> DataList => _dataList;

    public itemConfig_ItemEnum GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public itemConfig_ItemEnum Get(string key) => _dataMap[key];
    public itemConfig_ItemEnum this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

