
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_transmit
{
    private readonly System.Collections.Generic.Dictionary<int, transmitConfig_transmit> _dataMap;
    private readonly System.Collections.Generic.List<transmitConfig_transmit> _dataList;
    
    public Table_transmit(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, transmitConfig_transmit>();
        _dataList = new System.Collections.Generic.List<transmitConfig_transmit>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            transmitConfig_transmit _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = transmitConfig_transmit.DeserializetransmitConfig_transmit(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, transmitConfig_transmit> DataMap => _dataMap;
    public System.Collections.Generic.List<transmitConfig_transmit> DataList => _dataList;

    public transmitConfig_transmit GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public transmitConfig_transmit Get(int key) => _dataMap[key];
    public transmitConfig_transmit this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

