
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_AbilityRescompetenceConfi
{
    private readonly System.Collections.Generic.Dictionary<int, competenceConfig_AbilityRes> _dataMap;
    private readonly System.Collections.Generic.List<competenceConfig_AbilityRes> _dataList;
    
    public Table_AbilityRescompetenceConfi(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, competenceConfig_AbilityRes>();
        _dataList = new System.Collections.Generic.List<competenceConfig_AbilityRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            competenceConfig_AbilityRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = competenceConfig_AbilityRes.DeserializecompetenceConfig_AbilityRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, competenceConfig_AbilityRes> DataMap => _dataMap;
    public System.Collections.Generic.List<competenceConfig_AbilityRes> DataList => _dataList;

    public competenceConfig_AbilityRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public competenceConfig_AbilityRes Get(int key) => _dataMap[key];
    public competenceConfig_AbilityRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

