
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Table_NestReslevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, levelConfig_NestRes> _dataMap;
    private readonly System.Collections.Generic.List<levelConfig_NestRes> _dataList;
    
    public Table_NestReslevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, levelConfig_NestRes>();
        _dataList = new System.Collections.Generic.List<levelConfig_NestRes>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            levelConfig_NestRes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = levelConfig_NestRes.DeserializelevelConfig_NestRes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, levelConfig_NestRes> DataMap => _dataMap;
    public System.Collections.Generic.List<levelConfig_NestRes> DataList => _dataList;

    public levelConfig_NestRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public levelConfig_NestRes Get(int key) => _dataMap[key];
    public levelConfig_NestRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

