
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class turntableConfig : Luban.BeanBase
{
    public turntableConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["money"].IsNumber) { throw new SerializationException(); }  Money = _buf["money"]; }
    }

    public static turntableConfig DeserializeturntableConfig(JSONNode _buf)
    {
        return new turntableConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 奖励倍数
    /// </summary>
    public readonly int Money;
   
    public const int __ID__ = 1788303379;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "money:" + Money + ","
        + "}";
    }
}

}

